export const fontSize = {
  h1: 'var(--font-size-headline-1)',
  h2: 'var(--font-size-headline-2)',
  h3: 'var(--font-size-headline-3)',
  h4: 'var(--font-size-headline-4)',
  h5: 'var(--font-size-headline-5)',
  t1: 'var(--font-size-title-1)',
  t2: 'var(--font-size-title-2)',
  t3: 'var(--font-size-title-3)',
  t4: 'var(--font-size-title-4)',
  b1: 'var(--font-size-body-1)',
  b2: 'var(--font-size-body-2)',
  b3: 'var(--font-size-body-3)',
  b4: 'var(--font-size-body-4)',
  b5: 'var(--font-size-body-5)',
  a1: 'var(--font-size-additional-1)',
}
